### ISSUE TITLE
Add parameters to search page

### ISSUE THREAD

**Issue by Mitsuko86** [gmoz22/facebook-marketplace-nationwide#11]
Is it possible to add Facebook filter parameters to the search? For example, Condition, Date Listed & Price Range.

Also, if possible, I think a Ship to you parameter would be great to add.

**Comment by gmoz22** [comment]
@Mitsuko86 I just added support for filtering by: Sort By, Days Since Listed, Availability and Condition. I'll see about Shipping too.
