### ISSUE TITLE
Add Brazil (17 cities)

### ISSUE THREAD

**Issue by kwbr1** [gmoz22/facebook-marketplace-nationwide#12]
Hello. Thanks for great work.
Would it be possible to add Brazil to the website?
I've identified 17 cities that together can cover the entire territory of Brazil (I just skipped an area where basically the entire population is indigenous).

If that helps in any way:
"São Sebastião do Oeste" 500km
"Jacutinga, PR" 500km
"Encruzilhada do Sul" 500km
"Geraizinho, MG" 500km
"Tupanaci, PE" 500km
"Cabeceira Velha, BA" 500km
"Jaupaci, Goias" 500km
"Tangará da Serra" 500km
"Goianésia do Pará" 500km
"Azauri, PA" 500km
"Rorainópolis" 500km
"Japurá (Amazonas)" 500km
"Ponta Alegre, AM" 500km
"São João, RO" 500km
"São Antonio, AC" 500km
"Três Bocas, AM" 500km
"Aquidauana" 250km

Thank you.

**Comment by gmoz22** [comment]
Thanks for the help, ended up adjusting to use 18 tabs for fuller coverage. Pushing it to the site.
