### ISSUE TITLE
Only Opens One Tab

### ISSUE THREAD

**Issue by FredlandSupplyCompany** [gmoz22/facebook-marketplace-nationwide#20]
Hello, this used to work great! It now only opens one tab at a time. I hope you can fix it!

**Comment by colliderman** [comment]
Came here to say the same thing! With this latest update it's only opening a single tab and searching one area whereas before it was opening multiple tabs and searching all areas. Only tried with Chrome.

**Comment by gmoz22** [comment]
@FredlandSupplyCompany the URL has changed so you need to allow your browser to open multiple tabs for the new domain.

On Google Chrome, check the "Pop-up blocked" icon on the right side of the address bar, looks like a window with a diagonal bar through it, and "Allow multiple tabs to open". If you don't see it, go to Settings > Privacy and security > Content > Pop-ups and redirects and manually add the site "http://fbmpns.gmoz.biz/" to the list of sites "allowed to send pop-ups and use redirects".

**Comment by FredlandSupplyCompany** [comment]
That fixed it. Thanks!
