### ISSUE TITLE
Local vs shipping results not working correctly 

### ISSUE THREAD

**Issue by Jonathan1171** [gmoz22/facebook-marketplace-nationwide#21]
It seems that it will always show results with shipping. Thank you for your work on this app. Very well done.

**Comment by gmoz22** [comment]
@Jonathan1171 Thank you. I'm getting some odd behavior in Marketplace where the Delivery option doesn't appear when logged in and does appear when logged out. When I use the tool logged in, the pickup option lists all results and the shipping one doesn't yield any results. Are you getting similar behavior?

**Comment by Jonathan1171** [comment]
I just checked on my desktop computer (windows 11 and using Google chrome)
. When im logged out it behaves normally. When I'm logging in it gives me
ship items.

**Comment by gmoz22** [comment]
@Jonathan1171 The Delivery option is just not available when logged in at the moment and passing the URL parameters does not affect the results as it would before.

<img width="347" alt="image" src="https://github.com/user-attachments/assets/bd8985f3-0b40-4e7e-8d9a-710d0b5f524c">

I'm not sure if this is a Marketplace bug or if they are doing some changes but unfortunately this is not something I can fix. 

Also when I try a search on Marketplace while logged out, if Delivery is set to All I get plenty of results, with Local Pickup I get less results, but with Shipping I get no results at all so this looks buggy as well :/ Hopefully this is just a temporary issue with their system.

**Comment by Jonathan1171** [comment]
Thank you

**Comment by swirle13** [comment]
Running into this bug too. When selecting the shipping method to be local only via the UI, the following search arg is added to the URL: `&deliveryMethod=local_pick_up`. When set to shipping only, it is `&deliveryMethod=shipping`, and by default and the "all" setting, the query is not present in the url.

I'm not sure how you structure the queries, but perhaps manually adding this additional search field to the url before opening could fix it?

**Comment by gmoz22** [comment]
Fixed via #21, thanks @swirle13!

**Comment by swirle13** [comment]
@gmoz22 you're very welcome! Spent a good hour that night diving into how your site worked as I'm not a frontend guy, though I have experience from having my own Typescript/React side project 😁
