### ISSUE TITLE
Add UK and NZ

### ISSUE THREAD

**Issue by Orcamm** [gmoz22/facebook-marketplace-nationwide#9]
Howdy, any chance of getting the United Kingdom and New Zealand added?

**Comment by gmoz22** [comment]
Sure! They shouldn't take too long, stay tuned.

**Comment by Orcamm** [comment]
Possibly also Germany and France? Or Netherlands? Thanks!

**Comment by Orcamm** [comment]
Hi, any update on adding more countries?

**Comment by gmoz22** [comment]
@Orcamm I haven't had the time to get to it, I'll schedule some time in January

**Comment by gmoz22** [comment]
@Orcamm Added United Kingdom, New Zealand and France!
Germany can be done with 1 tab with 500km radius from Kassel, and Netherlands can be done with 1 tab with 500km radius from Amsterdam, but I'm considering adding them.
